### ISSUE TITLE
SQL injection in query

### ISSUE THREAD

**Issue by scarfunk** [Knowre-Dev/swint-query#8]
모 회사의 해킹 뉴스(?) 를 접하고 공부를 하다가 궁금해서 남깁니다.

fetch, save, remove 등의 메소드는 방어가 되는걸로 아는데요.
query method 에는 특별한 injection 방어법이 존재하는지요?
사실 프로덕트 단에서 query 메소드를 꽤 자주 사용하고 있어서요..

```javascript
it('test SQL injection', function (done) {
		var injectString = `'' OR 1 = 1`;
		var fetchQry = `SELECT * from foos where id = ${injectString}`;
		models.foo.query(fetchQry, function (err, result) {
			print(result);
			done();
		});
	});
```

**Comment by chosh31** [comment]
query 관련 메소드는 fetch, save, remove 등에서 내부적으로 호출하기 위해서 단순 sql 실행용입니다.
아마 fetch 메소드를 사용을 하여 우선 최소한 방어를 시키는 것으로 변경이 필요할 듯 합니다.

추후 swint-query 에도 sql injection 관련 보완이 필요한 듯 합니다.

**Comment by scarfunk** [comment]
그렇군요. query 는 주의 해서 사용해야 하겠군요.

**Comment by chosh31** [comment]
sql escape 문자열로 인한 에러 발생으로 위와 관련된 사항이 다시 이슈화 됨.


석규쌤 코멘트

```
음 swint-query 에서 query(raw)메소드 에서 escape 를 처리못해서
간밤에 에러가 하나 났었네요. Don't like... 같은 구문이 들어옴.
sql인젝션 취약점이 있는건 알았는데. 의도된 공격은 아니지만 터지긴하네요.ㅠㅠ
일단은 그냥 라우터단에서 생으로
require('mysql).escape(text) 같이 해놓는게 땜질은 될거 같긴한데..
좋은 의견이 혹시 있으신가요.
labs 와도 연관되있어 공개적으로 남겨봅니다...
```

**Comment by scarfunk** [comment]
오 과거의 유산이...
시퀄라이즈 알못인데 그쪽은 raw 쿼리해도 괜찮나 궁금하군요. @graynun 님을 소환 해봅니다.

**Comment by graynun** [comment]
띠용맨 소환되어서 와보았습니다. 한국서버의 경우 raw query를 사용하는 경우가 거의 없어서 생각해 본 적이 없는데 한번 검색해보겠습니다.

**Comment by graynun** [comment]
벼락치기로 훑어보니 raw query의 경우 sequelize 내부의 query generator를 안타서 escape가 안될 것 같긴 한데,,,, 나중에 시간나면 한 번 실험해보도록 하겠습니다....!

**Comment by scarfunk** [comment]
시퀄에서도 불가능한 영역일것이라고 믿습니다.
escape 를 하느냐 마느냐는 휴먼이 정하는거고. 결국 라이브러리는 sql 문자열 하나만 받는건데..
구분해 낼수가 없을듯.
그리고 시퀄에서 가능했다면 mysql 이 그걸 차용안할리도 없고...

**Comment by chosh31** [comment]
위 escape 관련하여 

query 자체에서는 완성된 sql문을 통해서 해당 escape 문자열이 어느부분에 있는 문자열인지 확인할 수 없는 문제로 인해 현재 프러덕트 단에서 처리하는 방식으로 우선 하도록 얘기되었습니다.

swint-query 에서 prepared statement sql방식도 지원하도록 업데이트 진행하기로 하였습니다.
- 추후 가이드 별도로 필요

최종적인 목적은 fetch/save 등에서 별도로 created_at 등을 핸들링 가능할 수 있는 옵션이 별도로 필요할 것으로 보임.

**Comment by chosh31** [comment]
swint-query 에서 prepared statement sql방식 지원 및 가이드 적용 - PR #24
